Alice: # Person name

  Interferometer: # device name

    Connection: # Parameters
      # LADAq2:
      # - IntE
      # - IntF
    Interferometers:
      IntA:
        com_port: Null
        IP: Null
        IntName: IntA
        Out1: -1
        Out2: -5
        Phase0Voltage: 3.1
        Phase0power: 0.0005904458
        Phase180Voltage: 3.67
        Phase180power: 0.0017175367777777777
        Phase270Voltage: 3.92
        Phase270power: 0.0011574313333333334
        Phase90Voltage: 3.41
        Phase90power: 0.0011899726666666664
        V: 3.67
        VSrcCh: 0
      IntB:
        com_port: Null
        IP: Null
        IntName: IntB
        Out1: -2
        Out2: -6
        Phase0Voltage: 3.1
        Phase0power: 0.0005904458
        Phase180Voltage: 3.67
        Phase180power: 0.0017175367777777777
        Phase270Voltage: 3.92
        Phase270power: 0.0011574313333333334
        Phase90Voltage: 3.41
        Phase90power: 0.0011899726666666664
        V: 3.67
        VSrcCh: 1
      IntC:
        com_port: /dev/ttyACM0
        IP: Null
        IntName: IntC
        Out1: -3
        Out2: -7
        Phase0Voltage: 0.0
        Phase0power: 0.0
        Phase180Voltage: 0.0
        Phase180power: 0.0
        Phase270Voltage: 0.0
        Phase270power: 0.0
        Phase90Voltage: 0.0
        Phase90power: 0.0
        V: 0.2
        VSrcCh: 2
      IntD:
        com_port: Null
        IP: Null
        IntName: IntD
        Out1: -3
        Out2: -7
        Phase0Voltage: 3.100000000000001
        Phase0power: 0.0011844089
        Phase180Voltage: 3.7000000000000015
        Phase180power: 2.39562769e-06
        Phase270Voltage: 0.0
        Phase270power: 0.0
        Phase90Voltage: 0.0
        Phase90power: 0.0
        V: 2.8
        VSrcCh: 0
      IntE:
        com_port: Null
        IP: Null
        IntName: IntE
        Out1: 2
        Out2: 3
        Phase0Voltage: 2.9574999999999956
        Phase0power: 0.001292980655
        Phase180Voltage: 3.494999999999984
        Phase180power: 1.570858017904762e-05
        Phase270Voltage: 3.7249999999999788
        Phase270power: 0.0006577415531100002
        Phase90Voltage: 3.247499999999989
        Phase90power: 0.0006577415531100002
        V: 2.17
        VSrcCh: 0
      IntF:
        com_port: Null
        IP: Null
        IntName: IntF
        Out1: 5
        Out2: 6
        Phase0Voltage: 0.1
        Phase0power: 0.0005904458
        Phase180Voltage: 0.1
        Phase180power: 0.0017175367777777777
        Phase270Voltage: 0.1
        Phase270power: 0.0011574313333333334
        Phase90Voltage: 0.1
        Phase90power: 0.0011899726666666664
        V: 2.5
        VSrcCh: 1
    LADAqs:
      LADAq2:
        com_port: /dev/ttyACM0

  Optical Switch: # device (leave a space between devices)
    com_port: Null # Parameters
    SW1: ON
    SW2: OFF
    SW3: ON
    SW4: OFF

  Time Tagger: #device
    Channels: # Parameters
      Ch1:
        ChannelID: 1
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
      Ch2:
        ChannelID: -2
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
      Ch3:
        ChannelID: -3
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
      Ch5:
        ChannelID: -5
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 64500  # in ps
      Clk:
        ChannelID: -4
        TriggerLevel: 0.4  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
    DataAcquisitionTime: 1  # in seconds

  Laser:
    port: ttyUSB0
    baud_rate: 9600
    min_pow: 600
    max_pow: 1700
    wavelength: 1550
    power: 6

Bob:

  Time Tagger: #device
    Channels: # Parameters
      Ch1:
        ChannelID: 1
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
      Ch2:
        ChannelID: -2
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
      Ch3:
        ChannelID: -3
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
      Ch5:
        ChannelID: -5
        TriggerLevel: -0.07  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 64500  # in ps
      Clk:
        ChannelID: -4
        TriggerLevel: 0.4  # in volts
        Deadtime: 100000  # in ps
        DelayTime: 0  # in ps
    DataAcquisitionTime: 1  # in seconds

  Optical Switch: # device
    com_port: Null # Parameters
    SW1: ON
    SW2: OFF
    SW3: ON
    SW4: OFF

Charlie: # leave a space (like above) to seperate different persons

  Optical Switch: #device
    com_port: Null # Parameters
    SW1: ON
    SW2: OFF
    SW3: ON
    SW4: OFF